apiVersion: apps/v1 #version of the API to use
kind: Deployment #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: openjdk-deployment #Name of the deployment
  labels: #A tag on the deployments created
    app: openjdk
spec: #specifications for our object
  replicas: 2 #The number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: openjdk #any pods with labels matching this I'm responsible for.
  template: #The pod template that gets deployed
    metadata:
      labels: #A tag on the replica sets created
        app: openjdk
    spec:
      containers:
      - name: openjdk-container #the name of the container within the pod
        image: openjdk #which container image should be pulled
        ports:
        - containerPort: 1880 #the port of the container within the pod
---
apiVersion: v1 #version of the API to use
kind: Service #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: openjdk-nginx #Name of the service
spec: #specifications for our object
  type: NodePort #Ignore for now discussed in a future post
  ports: #Ignore for now discussed in a future post
  - name: openjdk
    port: 1880
    targetPort: 1880
#    nodePort: 30002
    protocol: TCP
  selector: #Label selector used to identify pods
    app: openjdk
